baseURL = 'https://base.url/'
languageCode = 'en-us'
title = 'Title of Website'
theme = "barebones"
keywords = "homepage, composer, sound art"
# logo = 'logos/mk-logo-light.png'

# Directory name of your blog content (default is `content/posts`)
contentTypeName = "blog"

[outputs]
home = ["html", "rss"]

[minify]
minifyOutput = true

[[menu.main]]
identifier = "projects"
name       = "projects"
url        = "/portfolio"
weight = 1

[[menu.main]]
identifier = "services"
name       = "services"
url        = "/services"
weight = 2


# Site parameters
[params]

# Sub title
subtitle = ''

# Description
description = ''
